### PR TITLE
Update wallaby.js

### PR DESCRIPTION
**Pull request by ArtemGovorov**

### CODE REVIEW

**Comment by nibblesnbits** [comment]
It's now giving me this:

```
Error: Cannot find module "../maps/decode.json"​​
​​at http://localhost:57359/__modules/41.js?1486163049509:1​​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/AppMessages.spec.js:2:0​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/AuthGuard.spec.js:2:0​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/CartProductDisplay.spec.js:2:0​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/CartProductList.spec.js:2:0​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/CartSummary.spec.js:2:0​
​​Error: Cannot find module "../maps/decode.json"​​
  at ​src/components/EditProductForm.spec.js:2:0​
​​Module not found: Error: Cannot resolve module 'react/addons' in c:\dump\slingshot-sagas\node_modules\enzyme\buildModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/addons' in c:\dump\slingshot-sagas\node_modules\enzyme\build​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\lib\Compilation.js:229:38​​
​​  at onDoneResolving (c:\dump\slingshot-sagas\node_modules\webpack\lib\NormalModuleFactory.js:29:20)​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\lib\NormalModuleFactory.js:85:20​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:726:13​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:52:16​​
​​  at done (c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:241:17)​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:44:16​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:723:17​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:167:37​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19​​
​​  at onResolved (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:38:18)​​
​​  at innerCallback (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:94:11)​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:54:23​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:191:15​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:45:26​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:122:33​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:191:15​​
​​  at applyPluginsParallelBailResult.createInnerCallback.log (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:110:4)​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at Tapable.<anonymous> (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\DirectoryDescriptionFilePlugin.js:24:12)​​
​​  at Storage.finished (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)​​
​​  at ReadFileContext.callback (c:\dump\slingshot-sagas\node_modules\graceful-fs\graceful-fs.js:78:16)​​
​​  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)​​
​​​​
​​Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in c:\dump\slingshot-sagas\node_modules\enzyme\buildModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in c:\dump\slingshot-sagas\node_modules\enzyme\build​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\lib\Compilation.js:229:38​​
​​  at onDoneResolving (c:\dump\slingshot-sagas\node_modules\webpack\lib\NormalModuleFactory.js:29:20)​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\lib\NormalModuleFactory.js:85:20​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:726:13​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:52:16​​
​​  at done (c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:241:17)​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:44:16​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:723:17​​
​​  at c:\dump\slingshot-sagas\node_modules\webpack\node_modules\async\lib\async.js:167:37​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19​​
​​  at onResolved (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:38:18)​​
​​  at innerCallback (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:94:11)​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:54:23​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:191:15​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:45:26​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:122:33​​
​​  at c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:191:15​​
​​  at applyPluginsParallelBailResult.createInnerCallback.log (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\Resolver.js:110:4)​​
​​  at loggingCallbackWrapper (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)​​
​​  at c:\dump\slingshot-sagas\node_modules\tapable\lib\Tapable.js:134:6​​
​​  at Tapable.<anonymous> (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\DirectoryDescriptionFilePlugin.js:24:12)​​
​​  at Storage.finished (c:\dump\slingshot-sagas\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)​​
​​  at ReadFileContext.callback (c:\dump\slingshot-sagas\node_modules\graceful-fs\graceful-fs.js:78:16)​​
​​  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)​​
​​​​
```
....etc

**Comment by ArtemGovorov** [comment]
There's no `src/components/EditProductForm.spec.js` file in the repo, so I can't reproduce it.
Nevertheless, I updated the config just by guessing what's going on from the error messages.
Note that you need to include all files (except node modules) that are used in your tests to the `files` list, in this change I have added `*.json`, you may also need to add `*.css` or whatever other files you import with webpack.

Please also update the repo if it's not working for you, so I could reproduce it.

**Comment by ArtemGovorov** [comment]
BTW, I have noticed you're using mocha with node for testing in the repo. You may [do the same in wallaby](https://wallabyjs.com/docs/integration/node.html) without having to configure webpack:

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.js'},
      {pattern: 'src/**/*.spec.js', ignore: true},
    ],

    tests: [
      {pattern: 'src/**/*.spec.js'},
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    debug: true,

    setup: function () {
      process.env.NODE_ENV = 'test';
      require('jsdom-global/register');
      require('babel-polyfill');

      ['.css', '.scss', '.png', '.jpg'].forEach(ext => {
        require.extensions[ext] = () => null;
      });
    }
  };
};

```

**Comment by nibblesnbits** [comment]
That mocha setup works perfectly!  Much better than the Webpack version.  Thanks a ton!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Pull request closed without merging**
